---
- hosts: all
  name: Baseline Apache Configuration
  become: yes
  vars:
    epel: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    base_packages:
      - vim
      - git
      - python-pip
      - unzip
      - java-1.7.0-openjdk
      - libselinux-python
      - libsemanage-python
    httpd_packages:
      - httpd
      - mod_wsgi
    apache_test_message: This is a test message
    apache_max_keep_alive_requests: 115

  tasks:
    - name: enable epel
      yum:
        name: "{{epel}}"
        state: present

    - name: base packages are present
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ base_packages }}"

    - name: httpd packages are present
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ httpd_packages }}"
      notify: restart apache service

    - name: site-enabled directory is present
      file:
        name: /etc/httpd/conf/sites-enabled
        state: directory

    - name: latest httpd.conf is present
      template:
        src: templates/httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
      notify: restart apache service

    - name: latest index.html is present
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html

    - name: httpd is started and enabled
      service:
        name: httpd
        state: started
        enabled: yes

  handlers:
    - name: restart apache service
      service:
        name: httpd
        state: restarted
